# Generated by Django 3.2.8 on 2021-10-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата сдачи'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='execute',
            field=models.BooleanField(default=False, verbose_name='Отметка'),
        ),
    ]
